import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import Layout from "../components/layout/Layout";

const drawerWidth = 240;

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "シフト管理アプリ",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        <AppRouterCacheProvider>
          <Box sx={{ display: "flex", bgcolor: "#e8eaf6", minHeight: "100vh" }}>
            <CssBaseline />

            {/* ヘッダー と サイドバー*/}
            <Layout />

            {/* メインコンテンツ */}
            <Box component="main" sx={{ flexGrow: 1, p: 3, width: { sm: `calc(100% - ${drawerWidth}px)` } }}>
              <Toolbar />
              {children}
            </Box>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
